# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54cebfeac1892157cff9ce0212f01f01350984bff17f5091919fadeb17a9ef0ca4938453edfa7931b30b2ce0b51a7e4fe404d0db2a10325cf55018ae858bd1da

test:
  secret_key_base: 173448251ba8c548917964b45b17000fb566d4902ed3768d2d74e524a4948c694669721d679ee085ea069927c481d9e9b578c19d67253a293ebef1a9379a5379

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
